### ISSUE TITLE
Add circos plot for cell composition in SeruatClusterStats

### ISSUE THREAD

**Issue by pwwang** [pwwang/immunopipe#46]
Example (right pane):

![example](https://medicine.umich.edu/sites/default/files/Nunez%2C%20Gabriel%20Pub_Image1_3.jpg)

@yuey11

**Comment by pwwang** [comment]
@yuey11 

Added in [v1.3.1](https://github.com/pwwang/immunopipe/releases/tag/1.3.1).

A typical configuration could look like this:

https://github.com/pwwang/immunopipe-example/blob/50cf503e4ad413d7417270bc034623a36c1e4faa/Immunopipe.config.toml#L68-L72

```toml
[SeuratClusterStats.envs.stats."Composition of cell types in Tumor samples"]
subset = 'source == "Tumor"'
circos = true
ident = "seurat_clusters"
group-by = "patient"
```

The plot would look like this:

![](https://github.com/pwwang/immunopipe-example/blob/master/output/SeuratClusterStats/samples.seurat.annotated.tessa.cluster_stats/stats/Composition-of-cell-types-in-Tumor-samples.circos.png?raw=true)
